services:
  - type: web
    name: elementary-learning-app 1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/learning.db
